# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googform', '0003_auto_20161109_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='workshop',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
