# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googform', '0004_knowledge_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
