# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googform', '0006_auto_20161110_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='topics',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
