# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googform', '0008_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='topics',
            field=models.ManyToManyField(to='googform.Topics'),
        ),
    ]
